// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext } from '../storyblok.d.ts';
export interface StoryblokAddressBlock {
  address1Title: string;
  address1: string;
  address2Title: string;
  address2: string;
  followUsTitle: string;
  followUsLabel: string;
  followUsLink: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "addressBlock";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokContactBlock {
  title: string;
  variant?: "" | "large" | "default" | "box" | "header";
  background?: "" | "red" | "yellow";
  email: string;
  phone1: string;
  phone2?: string;
  noTopPadding?: boolean;
  noBottomPadding?: boolean;
  inContainer?: boolean;
  component: "contactBlock";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokContentBlock {
  title?: string;
  intro?: string;
  content?: StoryblokRichtext;
  callToActionLink?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  callToActionLabel?: string;
  usedAsHeader?: boolean;
  image?: StoryblokAsset;
  boxed?: boolean;
  component: "contentBlock";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokContentContainer {
  title: string;
  body?: (
    | StoryblokAddressBlock
    | StoryblokContactBlock
    | StoryblokContentBlock
    | StoryblokContentContainer
    | StoryblokFooter
    | StoryblokHeader
    | StoryblokHeaderMenuAnchor
    | StoryblokHeaderMenuAnchorGroup
    | StoryblokHeaderMenuColumn
    | StoryblokHeaderMenuGroup
    | StoryblokHeaderMenuLink
    | StoryblokHero
    | StoryblokHeroLink
    | StoryblokImageBlock
    | StoryblokJob
    | StoryblokLatestPosts
    | StoryblokLegalContent
    | StoryblokPage
    | StoryblokPartner
    | StoryblokPartners
    | StoryblokPost
    | StoryblokServicePageHeader
    | StoryblokStep
    | StoryblokSteps
    | StoryblokTarget
    | StoryblokTargets
    | StoryblokTechnologies
    | StoryblokTechnology
    | StoryblokTechnologyContent
    | StoryblokUncoverWhatsNew
    | StoryblokWorkWithUs
  )[];
  component: "contentContainer";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokFooter {
  title: string;
  address1Title?: string;
  address1Line1?: string;
  address1Line2?: string;
  address2Title?: string;
  address2Line1?: string;
  address2Line2?: string;
  emailTitle?: string;
  email?: string;
  phoneTitle?: string;
  phone1?: string;
  phone2?: string;
  component: "footer";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokHeader {
  services?: StoryblokHeaderMenuColumn[];
  component: "header";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokHeaderMenuAnchor {
  label: string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "headerMenuAnchor";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokHeaderMenuAnchorGroup {
  body?: StoryblokHeaderMenuAnchor[];
  component: "headerMenuAnchorGroup";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokHeaderMenuColumn {
  body?: StoryblokHeaderMenuGroup[];
  component: "headerMenuColumn";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokHeaderMenuGroup {
  hasAnchorGroup?: boolean;
  body?: (StoryblokHeaderMenuLink | StoryblokHeaderMenuAnchorGroup)[];
  component: "headerMenuGroup";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokHeaderMenuLink {
  label: string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "headerMenuLink";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokHero {
  title: string;
  background: StoryblokAsset;
  poster: StoryblokAsset;
  links?: StoryblokHeroLink[];
  component: "hero";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokHeroLink {
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label: string;
  image: StoryblokAsset;
  component: "heroLink";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokImageBlock {
  image: StoryblokAsset;
  component: "imageBlock";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokJob {
  title: string;
  publishDate: string;
  excerpt: string;
  moreDetailsLabel: string;
  moreDetailsLink: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "job";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokLatestPosts {
  title: string;
  allNewsLinkLabel: string;
  allNewsLink: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  count: string;
  component: "latestPosts";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokLegalContent {
  title: string;
  content?: StoryblokRichtext;
  component: "legalContent";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokPage {
  body?: (
    | StoryblokAddressBlock
    | StoryblokContactBlock
    | StoryblokContentBlock
    | StoryblokContentContainer
    | StoryblokFooter
    | StoryblokHeader
    | StoryblokHeaderMenuAnchor
    | StoryblokHeaderMenuAnchorGroup
    | StoryblokHeaderMenuColumn
    | StoryblokHeaderMenuGroup
    | StoryblokHeaderMenuLink
    | StoryblokHero
    | StoryblokHeroLink
    | StoryblokImageBlock
    | StoryblokJob
    | StoryblokLatestPosts
    | StoryblokLegalContent
    | StoryblokPage
    | StoryblokPartner
    | StoryblokPartners
    | StoryblokPost
    | StoryblokServicePageHeader
    | StoryblokStep
    | StoryblokSteps
    | StoryblokTarget
    | StoryblokTargets
    | StoryblokTechnologies
    | StoryblokTechnology
    | StoryblokTechnologyContent
    | StoryblokUncoverWhatsNew
    | StoryblokWorkWithUs
  )[];
  noIndex?: boolean;
  header: ISbStoryData<StoryblokHeader> | string;
  headerOnGreyBackground?: boolean;
  metaDescription?: string;
  metaTitle?: string;
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokPartner {
  logo: StoryblokAsset;
  description: string;
  component: "partner";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokPartners {
  title: string;
  callToActionLabel?: string;
  callToActionLink?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  items?: StoryblokPartner[];
  component: "partners";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokPost {
  title: string;
  publishDate: string;
  excerpt: string;
  content: StoryblokRichtext;
  header?: ISbStoryData<StoryblokHeader> | string;
  footer?: StoryblokFooter[];
  component: "post";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokServicePageHeader {
  title: string;
  image: StoryblokAsset;
  component: "servicePageHeader";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokStep {
  title: string;
  number: string;
  subSteps: string;
  component: "step";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokSteps {
  title: string;
  items?: StoryblokStep[];
  component: "steps";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokTarget {
  title: string;
  number: string;
  content: string;
  component: "target";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokTargets {
  title: string;
  intro?: string;
  content?: string;
  items?: StoryblokTarget[];
  component: "targets";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokTechnologies {
  title: string;
  items?: StoryblokTechnology[];
  component: "technologies";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokTechnology {
  title: string;
  number: string;
  callToActionLabel?: string;
  callToActionLink?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  body?: StoryblokTechnologyContent[];
  component: "technology";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokTechnologyContent {
  header?: string;
  content?: string;
  image?: StoryblokAsset;
  imagePosition?: "" | "left" | "right" | "full";
  component: "technologyContent";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokUncoverWhatsNew {
  title: string;
  count: string;
  loadMoreLabel: string;
  component: "uncoverWhatsNew";
  _uid: string;
  [k: string]: any;
}

export interface StoryblokWorkWithUs {
  title: string;
  openPositionsLabel: string;
  items?: StoryblokJob[];
  component: "workWithUs";
  _uid: string;
  [k: string]: any;
}
